version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    # set splitd memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: smith
      POSTGRES_PASSWORD: pwd
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - local_net

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "smith@test.com"
      PGADMIN_DEFAULT_PASSWORD: "pwd"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - local_net

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001" # For MinIO console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    networks:
      - local_net
    volumes:
      - minio-data:/data # Persist data outside the container
    command: server /data --console-address ":9001"

volumes:
  postgres-data:
  pgadmin-data:
  minio-data:

networks:
  local_net:
    driver: bridge
